import Head from "next/head";
import TopBarSearch from "@/Components/TopBarSearch";
import LinkCard from "@/Components/LinkCard";
import {Spacer} from "@nextui-org/react";
import {useRouter} from "next/router";

export default function Search({results}) {
    const router = useRouter()
    return (
        <>
            <Head>
                <title>{router.query.arg} - searchDTU</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/tab.ico" />
            </Head>
            <TopBarSearch initialValue={(router.query.arg)}/>
            {
                results.map((notice, index) =>
                    <LinkCard
                        title={notice.title}
                        link={notice.link}
                        date={notice.date*1000}
                        summary={notice.summary}
                        key={index}/>
                )
            }
        </>
    )
}

export async function getServerSideProps(context) {
    let data = await fetch(
        `https://ap-south-1.aws.data.mongodb-api.com/app/app0-rvapt/endpoint/search?arg=${context.query.arg}`
    ).then(response => response.json())


    return {
        props: {
            results: data,
        }
    }
}